# HARD CODED IMPORTANT RULE: Keep code concise and meaningful
# - Remove unwanted/junky code and unnecessary lines
# - Each line must be valuable and to the point
# - Avoid bloated, illogical code - prefer 100 clean lines over 10000 junk lines
# - Author: Rishi Gupta
# - License: MIT

[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short -m "not integration"
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning
markers =
    integration: network/API dependent tests (excluded by default)
    unit: deterministic offline tests
    slow: marks tests as slow (deselect with '-m "not slow"')
    latency: latency benchmarks
    accuracy: accuracy tests
    fallback: fallback chain tests
